# Generated by Django 5.0.6 on 2024-05-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ComfortDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.CharField(max_length=10)),
                ('dev_id', models.CharField(max_length=10)),
                ('h0', models.PositiveSmallIntegerField()),
                ('h1', models.PositiveSmallIntegerField()),
                ('h2', models.PositiveSmallIntegerField()),
                ('h3', models.PositiveSmallIntegerField()),
                ('h4', models.PositiveSmallIntegerField()),
                ('h5', models.PositiveSmallIntegerField()),
                ('h6', models.PositiveSmallIntegerField()),
                ('h7', models.PositiveSmallIntegerField()),
                ('h8', models.PositiveSmallIntegerField()),
                ('h9', models.PositiveSmallIntegerField()),
                ('h10', models.PositiveSmallIntegerField()),
                ('h11', models.PositiveSmallIntegerField()),
                ('h12', models.PositiveSmallIntegerField()),
                ('h13', models.PositiveSmallIntegerField()),
                ('h14', models.PositiveSmallIntegerField()),
                ('h15', models.PositiveSmallIntegerField()),
                ('h16', models.PositiveSmallIntegerField()),
                ('h17', models.PositiveSmallIntegerField()),
                ('h18', models.PositiveSmallIntegerField()),
                ('h19', models.PositiveSmallIntegerField()),
                ('h20', models.PositiveSmallIntegerField()),
                ('h21', models.PositiveSmallIntegerField()),
                ('h22', models.PositiveSmallIntegerField()),
                ('h23', models.PositiveSmallIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.CharField(max_length=10)),
                ('dev_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('consumption', models.FloatField()),
                ('is_deferrable', models.SmallIntegerField()),
                ('min_usage_hours', models.SmallIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='UsageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.CharField(max_length=10)),
                ('dev_id', models.CharField(max_length=10)),
                ('h0', models.PositiveSmallIntegerField()),
                ('h1', models.PositiveSmallIntegerField()),
                ('h2', models.PositiveSmallIntegerField()),
                ('h3', models.PositiveSmallIntegerField()),
                ('h4', models.PositiveSmallIntegerField()),
                ('h5', models.PositiveSmallIntegerField()),
                ('h6', models.PositiveSmallIntegerField()),
                ('h7', models.PositiveSmallIntegerField()),
                ('h8', models.PositiveSmallIntegerField()),
                ('h9', models.PositiveSmallIntegerField()),
                ('h10', models.PositiveSmallIntegerField()),
                ('h11', models.PositiveSmallIntegerField()),
                ('h12', models.PositiveSmallIntegerField()),
                ('h13', models.PositiveSmallIntegerField()),
                ('h14', models.PositiveSmallIntegerField()),
                ('h15', models.PositiveSmallIntegerField()),
                ('h16', models.PositiveSmallIntegerField()),
                ('h17', models.PositiveSmallIntegerField()),
                ('h18', models.PositiveSmallIntegerField()),
                ('h19', models.PositiveSmallIntegerField()),
                ('h20', models.PositiveSmallIntegerField()),
                ('h21', models.PositiveSmallIntegerField()),
                ('h22', models.PositiveSmallIntegerField()),
                ('h23', models.PositiveSmallIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.dataset')),
            ],
        ),
    ]
