# Generated by Django 5.0.6 on 2024-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_comfortdefinition_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfortdefinition',
            name='ap_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='comfortdefinition',
            name='dev_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='ap_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='dev_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='is_deferrable',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='min_usage_hours',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usagedefinition',
            name='ap_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usagedefinition',
            name='dev_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
