INITIAL_SCHEDULE_CONSUMPTION_VECTOR = "INITIAL_SCHEDULE_CONSUMPTION_VECTOR"
COMPUTE_BASELINE_VALUES = "COMPUTE_BASELINE_VALUES"

COMPARE_INITIAL_AND_TARGET_CURVE = "COMPARE_INITIAL_AND_TARGET_CURVE"

DO_BI_LEVEL_OPTIMIZATION = "DO_BI_LEVEL_OPTIMIZATION"
DO_FIRST_LEVEL_OPTIMIZATION = "DO_FIRST_LEVEL_OPTIMIZATION"
DO_GREEDY_OPTIMIZATION = "DO_GREEDY_OPTIMIZATION"

GENERATE_DATASET = "GENERATE_DATASET"